version: '2'
services:
  nginx:
    build: ./docker/nginx-fpm
    image: schoren/nginx-fpm
    links:
      - phpfpm
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html

  phpfpm:
    build: ./docker/php56
    image: schoren/php56
    links:
      - pgsql
      - mysql
      - memcached
      - redis
    volumes:
      - ./app:/var/www/html
    environment:
      PG_HOST: pgsql
      MYSQL_HOST: mysql
      MEMCACHED_HOST: memcached
      REDIS_HOST: redis

      PG_DBNAME: app
      PG_USER: app
      PG_PASSWORD: 123

      MYSQL_DBNAME: app
      MYSQL_USER: app
      MYSQL_PASSWORD: 123

  pgsql:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: app
      POSTGRES_PASSWORD: 123

  mysql:
    image: mariadb
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: 123

  memcached:
    image: memcached

  redis:
    build: docker/redis
    image: schoren/redis
    volumes:
      - /data